events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:3001;
    }

    upstream notification_service {
        server notification-service:3002;
    }

    upstream analytics_service {
        server analytics-service:8081;
    }

    upstream report_service {
        server report-service:3003;
    }

    upstream multimedia_service {
        server multimedia-service:3004;
    }

    server {
        listen 8000;

        location /health {
            return 200 '{"status": "API Gateway is running"}';
            add_header Content-Type application/json;
        }

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /reports/ {
            proxy_pass http://report_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /notify/ {
            proxy_pass http://notification_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /analytics/ {
            proxy_pass http://analytics_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /multimedia/ {
            # Maps /multimedia/upload -> http://multimedia-service:3004/upload
            proxy_pass http://multimedia_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
